% Adams-Moulton One-Step Function
function [t,u]=amonestep(f,tspan,y0,Nh,varargin)
% Code below generated by MATLAB Copilot, and then edited multiple times...
% Understood and Tested before Fully Accepted
h = (tspan(2) - tspan(1))/Nh; % Step size
t = linspace(tspan(1), tspan(2), Nh+1); % Create time vector
u = zeros(length(y0), Nh+1); % Initialize solution array
u(:,1) = y0; % Set initial condition
for n = 1:Nh
    % Compute the next time step using the Adams-Moulton method
    u(:,n+1) = u(:,n) + h * (f(t(n+1), u(:,n)) + f(t(n), u(:,n))) / 2; % Update solution
end
end

