% Function code generated by Matlab Copilot from comment prompt
function L = cholesky_d(A) 
if ~isequal(A, A') || any(eig(A) <= 0)
    error('Matrix must be symmetric positive definite.');
end
n = size(A, 1);
L = zeros(n);
for i = 1:n
    for j = 1:i
        if i == j
            L(i, j) = sqrt(A(i, i) - sum(L(i, 1:j-1).^2));
        else
            L(i, j) = (A(i, j) - sum(L(i, 1:j-1) .* L(j, 1:j-1))) / L(j, j);
        end
    end
end
end
