%% Exercise 1
y_3=1+(24/60)+(51/60^2)+(10/60^3); % Approximation given to approximate sqrt(2) at the beginning of assignment
y=sqrt(2); % y=sqrt(a) so when a=2 y=sqrt(2)
e_abs=abs(y_3-y) % Absolute error is computed by finding the absolute value of the difference between y_n and y
e_rel=abs(y_3-y)/abs(y) % Relative error is computed by dividing the absolute error equation by the absolute value of y

%% Exercise 2
% See write up

%% Exercise 3

% Layout of code derived from pg.15 of A Friendly Introduction to Numerical Analysis by Brian Bradie 

a=2; % Approximate the square root of this number (a)
y0=1; % Chosen initial guess from approximation given
N=6; % The number of iterations asked for in Excercise 3 to approximate sqrt(2)

for i=1:N % Complete N iterations of loop, then end loop
    y0=0.5*(y0+(a/y0)); % Newton-Raphson method used to approximate sqrt(2)
    y_n=y0; % Store approximation value derived from Newton-Raphson method before completing next iteration
    e_abs1 = abs(y_n - y); % Each time an interation is completed in this loop, update the absolute error to the new value from this equation
    e_rel1 = e_abs1 / abs(y); % Each time an iteration is completed in this loop, update the relative error to the new value from this equation
    approx_abs = abs(y_3-y0);
    approx_rel=approx_abs/abs(y_3);
    fprintf('Iteration %d: y_n = %.10f, e_abs = %.10e, e_rel = %.10e, approx_abs=%.10e, approx_rel=%.10e\n', i, y_n, e_abs1, e_rel1,approx_abs,approx_rel); 
    % Print the iteration number (1 through 6), corresponding y_n value, and the
    % absolute and relative error at each iteration 
end

% For-loop code suggested and generated by Matlab Copilot based off of input variables (a,y0,N) and their corresponding comments,
% and code/comments from Exercise 1. Comments that may have been generated in loop by Copilot were either
% rephrased into own words and/or new comments were added to describe code behavior in more depth

% plot relative error e_rel1 on log scale
loglog(1:6, e_rel1, '-o'); % how to plot log to log scale from https://www.mathworks.com/help/matlab/ref/loglog.html
xlabel('Iteration Number'); % x-axis label
ylabel('Relative Error'); % y-axis label
grid("on"); % display grid on plot for easier visual of relative error

% The plot of e_rel by iterations 1 through 6 is not sensitive to initial
% y0 guess, but can introduce greater error the further away the initial
% guess is from the exact value

% Majority of relative error plot code above generated by Matlab Copilot, from comment
% "plot relative error e_rel


%% Exercise 6 and 7

delta_e0=6.0660171780e-02; % Initial estimate of error from Exercise 3 used for initial theoretical erorr estimate

for i=1:10 % Run loop for same number of iterations as script for algrothim
    delta_e0=0.5*(delta_e0)^2; % Take the value delta_e0 from each iteration and use theoretical estimate of error equation from excercise 5 with C=1/2
    delta_e=delta_e0; % Store each value of delta_e at each iteration
    fprintf('Iteration %d: delta_e = %.10e\n', i, delta_e); % Print the theoretical estimates of error for each iteration 1 through 10
end

% Lines 52-53 generated by Matlab Copilot from entry
% "delta_e0=6.0660171780e-02 for i=1:6 delta_e=0.5*(delta_e0)^2;"

%% Excercise 9
y_0=1.1; % Initial Guess

for i=1:20
    y_0=y_0+y_0^2-a; % Algorithm y_n+1 from exercise 9
    y_1=y_0; % Store approximate value
    fprintf('Iteration %d:y_1=%.10e\n',i,y_1); % Print findings
end

% If the initial guess to this algorithm is not the fixed point y_0=sqrt(2) then the
% algorithm does not converge, and diverges

%% Excercise 10

x0=1.1; % Initial Guess
for i=1:50
    x0=(1/4)*(3*x0+(2/x0)); % Algorithm x_n+1 from exercise 10
    x1=x0; % Store approximate value
    e_absx=abs(x1-sqrt(2)); % Calculate absolute error at each iteration
    e_relx=e_absx/abs(sqrt(2)); % Calculate relative error at each iteration
    fprintf('Iteration %d: x1=%.10f, e_absx=%.10e, e_relx=%.10e\n',i,x1,e_absx,e_relx) % Print findings
end

% This algrothim appropriately converges to sqrt(2) and does not diverge

z0=1.1; % Initial Guess
for i=1:20
    z0=(1/8)*(3*z0+(12/z0)-(4/z0^3)); % Algorithm z_n+1 from exercise 10
    z1=z0; % Store approximate value
    e_absz=abs(z1-sqrt(2)); % Calculate absolute error at each iteration
    e_relz=e_absz/abs(sqrt(2)); % Calculate relative error at each iteration
    fprintf('Iteration %d: z1=%.10f, e_absz=%.10e, e_relz=%.10e\n',i,z1,e_absz,e_relz) % Print findings
end

% This algorithm converges to sqrt(2) the fastest in the given algorithms
% from Exercise 10

w0=1.1; % Initial Guess
for i=1:20
    w0=w0*((w0^2+3*a)/(3*w0^2+a)); % Halley's method from https://en.wikipedia.org/wiki/Halley%27s_method#Use_of_Halley's_method_to_compute_square_roots
    w1=w0; % Store approximate value
    e_absw=abs(w1-sqrt(2)); % Calculate absolute error at each iteration
    e_relw=e_absw/abs(sqrt(2)); % Calculate relative error at each iteration
    fprintf('Iteration %d: w1=%.10f, e_absw=%.10e, e_relw=%.10e\n',i,w1,e_absw,e_relw) % Print findings
end




