tspan=[0,2*pi];
Nh=8;
y0=1;
% Define the ODE function to be solved
odefun = @(tspan, y) y*cos(tspan); % how to write odefun with @(tspan,y) was suggested from MATLAB Copilot
[t, y1] = feuler(odefun, tspan, y0, Nh);

fprintf("t|y\n-----------\n")
for n=1:length(t)
    fprintf("%4.2f|%9.6f\n",t(n),y1(n))
end

y_approx=max(y1)
t=1;
y_exact=exp(sin(t)); % From above symoblic ode solver
error_min_tspan=min(abs(y_exact-y1))
error_max_tspan=max(abs(y_exact-y1))


% store Nh and error before loop
% Idea for how to store and index Nh and error was from MATLAB Copilot, but I
% ultimately figured out how to index these in the loop in the correct way
error=zeros(1,n);
Nh=zeros(1,n);
for n=1:20
    Nh(n)=2^n;
    % section below was recommended by MATLAB Copilot
    [t, y1] = feuler(odefun, tspan, y0, Nh(n));
    error (n) = min(abs(y_exact - y1));
    % fprintf Nh value, y1, and error
    fprintf("Nh= %d, y(1) Approximation= %9.6f, Error at t=1; %9.6f\n", Nh(n), y1(end), error(n)); 
    %generated by Matlab Copilot from above prompt
end

% Plot error on log to log
h1=1./Nh;
figure;
loglog(1./Nh,error,'-')
xlabel("1/Nh")
ylabel("Error at t=1")