function [Q,R]=gs_factor(A) % Declare the function for Gram Schmidt
%X = [1 1 1; 0 1 1; 0 0 1]; % Example matrix from exercise 1 problem a)
[m, n] = size(A); % Set the rows and columns equal to the size of matrix X
Q = zeros(m, n); % Initialize 0 vectors within Q
R = zeros(m, n);
for j = 1:n % run the entire loop for 1 through n iterations
    v = A(:, j); % Begin loop with the jth column of matrix X
    for i = 1:j-1 % run inner loop from 1 to j-1 iterations
        r = Q(:, i)' * A(:, j); % Compute projection of Q onto X
        R(i, j) = Q(:, i)' * A(:, j); % Generated by Matlab Copilot
        v = v - r * Q(:, i); % Subtract projection from vector v
    end
    Q(:, j) = v / norm(v); % Generated by Matlab Copilot
    R(j, j) = norm(v); % Generated by Matlab Copilot
end
end
% 2 Matlab codes for gram_schmidt were generated by Matlab Copilot and combined, with adjustments
% made for problem. This was to follow algorithm sketch as close as possible. Comments were made in own words to explain algorithm.
% Needed clarification from Copilot to understand function of "'" symbol
% in Q(:,i). This link was also used to help calculate L2 norm https://mathworld.wolfram.com/L2-Norm.html


