f = @(t,y) 1-y+exp(2*t)*y.^2;

y0=0;
tspan=[0 0.9];

Nexact=100;
texact=linspace(tspan(1),tspan(2),Nexact);
uexact=exp(-texact).*tan(exp(texact)-1);
x=uexact;

% Opts layout was taken from MATLAB Drive class folder
opts=odeset('MinStep',1e-9,'MaxStep', 1e-1, 'InitialStep', .1,'RelTol',1e-5,'AbsTol',5e-7,'Stats','on');
[t,u]=ode45(f,tspan,y0,opts);
w=u;

err=abs(x-w);

% Below Generated by MATLAB Copilot
% plot error vs step-size, and store error at t=0.9
stepSizes = opts.MaxStep * (1 ./ (1:Nexact)); % Calculate step sizes
errorAtFinalTime = err(end); % Error at t=0.9
% Plot the error against the step sizes
figure;
loglog(stepSizes, err, 'o-');
xlabel('Step Size');
ylabel('Error');
title('Error vs Step Size');
grid on;


