m=16;
a=0.25;

% Chemostat ODEs, format with help from MATLAB Copilot
s_1 = @(t,s,x) 1-s-((m*s*x)./(a+s)); 
x_1= @(t,x,s) ((m*s*x)./(a+s))-x;

tspan=[0 , 12];

x0=0.02;
s0=0.5;

h=0.05;
Nh=(tspan(end)-tspan(1))./h;

% Below generated and recommendations from MATLAB Copilot into ode45 format from above data, 
% and then corrected and edited multiple times for rk4 method
[t, y] = rk4(@(t, y) [s_1(t, y(1), y(2)); x_1(t, y(2), y(1))], tspan, [s0; x0],Nh);
s = y(1, :);
x = y(2, :);

% Below Generated by MATLAB Copilot
figure;
plot(t, s, 'b', 'DisplayName', 'Substrate Concentration (s)');
hold on;
plot(t, x, 'r', 'DisplayName', 'Biomass Concentration (x)');
xlabel('Time');
ylabel('Concentration');
title('Step-Size h=0.05');
legend show;
grid on;

s12 = @(t1,s1,x1) 1-s1-((m*s1*x1)./(a+s1)); 
x12= @(t1,x1,s1) ((m*s1*x1)./(a+s1))-x1;

h1=0.06;
Nh1=(tspan(end)-tspan(1))/h1;

% Influenced, copy and pasted, and edited from part b of problem 3
[t1, y1] = rk4(@(t1, y1) [s12(t1, y1(1), y1(2)); x12(t1, y1(2), y1(1))], tspan, [s0; x0],Nh1);
s1 = y1(1,:);
x1 = y1(2,:);

% Below Generated by MATLAB Copilot
figure; hold on;
plot(t1, s1, 'b', 'DisplayName', 'Substrate Concentration (s)');
hold on;
plot(t1, x1, 'r', 'DisplayName', 'Biomass Concentration (x)');
xlabel('Time');
ylabel('Concentration');
title('Step-Size h=0.06');
legend show;
grid on;











