% Define grid for complex plane of interest with z=h*lambda
% From worksheet
L=3;
x=linspace(-L,L,301);
y=linspace(-L,L,301);
[X,Y]=meshgrid(x,y);
hLambda=X+1i*Y;

RK4=abs(1+hLambda+(1/2)*hLambda.^2+(1/6)*hLambda.^3+(1/24)*hLambda.^4);

figure;hold on;
% contour
% contour plot below generated by MATLAB Copilot from above comment and
% then edited for problem using Class Folder on MATLAB Drive
contourf(X, Y, RK4,[0,1],'LineColor','none'); hold on;
% plot point where x=0.1 and y=2i, below line generated by MATLAB Copilot
plot(0.1, 2, 'ro', 'MarkerSize', 8, 'MarkerFaceColor', 'r');
xlabel('Real Part');
ylabel('Imaginary Part');
title('Contour Plot of RK4');


