% Lines 2-13 were from a method of derivation found and learned on Google Gemini
syms x;
fx=log(x^2+1);

max_derivative=5;
derivatives=cell(max_derivative,1);

f=fx;
for n=1:max_derivative
    f=diff(f);
    derivatives{n}=f;
    fprintf('Derivative Order n=%d: %s\n',n,char(f)); 
end


for n=1:max_derivative
    x=1;
    derivativeValue = subs(derivatives{n}, x); % Generated by MATLAB Copilot
    fprintf('Derivative %d at x=1: %s\n', n, char(derivativeValue)); % Generated by MATLAB Copilot
end


x0=1;

h1=1;
D_h1=(log(x0^2+1)-log((x0-h1)^2+1))/h1

h2=.1;
D_h2=(log(x0^2+1)-log((x0-h2)^2+1))/h2

h3=0.01;
D_h3=(log(x0^2+1)-log((x0-h3)^2+1))/h3

h4=0.0001;
D_h4=(log(x0^2+1)-log((x0-h4)^2+1))/h4


%Method below from code in MATH 515 Class Folder
h=10.^(-1:-1:-8);
Dh1=(log(x0^2)-log(x0^2-h))./h;

error1=abs(D_h4-(2*x0)/(x0^2+1))

errorD_h=abs(D_h4-Dh1);

c=polyfit(log(h),log(errorD_h),1);
order_convergence=c(1)