% n equals 100 to 10^4 increasing by 100 each time
tStart=tic; % How to do tic toc command was taken from https://www.mathworks.com/help/matlab/ref/tic.html
T=zeros(1,length(n));
for n = 1:100 % For loop generated by Matlab Copilot from above comment
    A0=100*n;
    A = magic(A0); % define matrix A of magic square value at each n
    tic
    detA = det(A); % calculate the determinant of each A matrix
    fprintf('Determinant of %dx%d matrix: %f\n', n, n, detA); % display determinant value of each matrix A
    T(n)=toc;
end
tEnd=toc(tStart) % Display total time of determinant computation of loop in seconds
% Code below for semilogy generated by Matlab Copilot from above command
% Graph the time it takes for each matrix size
% Initialize T with zeros for the number of iterations
n=1:100;
T1=T(n);
% Find a constant C to approximate T(n) as C*n^3
% Calculate the constant C for the approximation %From Matlab Copilot
C=polyfit(log(n),log(T1),1);
C=C(1);

loglog(n, T1,n,C*n.^3); % From https://www.mathworks.com/help/matlab/ref/semilogy.html
xlabel('Matrix Size (n)');
ylabel('Time (seconds)');
title('Determinant Computation Time for Magic Squares');
grid on;

