% Cholesky decomposition algorithm
A=[16 -28 0;-28 53 10;0 10 29];
% References: Below Code generated by Matlab Copilot
L = choleskyDecomposition(A);
disp('Lower triangular matrix L:');
disp(L);
reconstructedA = L * L';
disp('Reconstructed matrix A:');
disp(reconstructedA);
if isequal(A, reconstructedA)
    disp('Reconstruction successful: A is equal to L * L''');
else
    disp('Reconstruction failed: A is not equal to L * L''');
end
% symmetric positive definite
% Check if matrix A is symmetric positive definite
if all(eig(A) > 0)
    disp('Matrix A is symmetric positive definite because all eigen values of A are greater than 0.');
else
    disp('Matrix A is not symmetric positive definite.');
end

B=[1 -2 3 -2;-2 20 -2 8;3 -2 11 -5;-2 8 -5 9];
% Below Code generated by Matlab Copilot
L1 = choleskyDecomposition(B);
disp('Lower triangular matrix L:');
disp(L1);
reconstructedB = L1 * L1';
disp('Reconstructed matrix B:');
disp(reconstructedB);
if isequal(B, reconstructedB)
    disp('Reconstruction successful: B is equal to L1 * L1''');
else
    disp('Reconstruction failed: B is not equal to L1 * L1''');
end
% symmetric positive definite
% Check if matrix A is symmetric positive definite
if all(eig(B) > 0)
    disp('Matrix B is symmetric positive definite because all eigen values of B are greater than 0.');
else
    disp('Matrix B is not symmetric positive definite.');
end
