for k=0:9
    epsilon=10^-k;
    A=[2 -2 0;epsilon-2 2 0;0 -1 3];
    x=[1 1 1]';
    b=A*x;
    % Display the results for each iteration
    fprintf('For k = %d, epsilon = %.1e, b = [%f; %f; %f]\n', k, epsilon, b); % Generated by Matlab Copilot
end