% Most of code was taken from Dr. Punit Gandhi's MATH 515 MATLAB folder, and
% manipulated to address Exercise 4 on Problem Set 3

xrng=[-1,3]; %interval
n=4; %n intervals, n+1 data points

funInterp=@(x) x.*exp(-x); %define function to approximate
funInterpPrime=@(x) exp(-x)+-x.*exp(-x); %define derivative

%% polynomial interpolations
%uniformly spaced points
xunif=linspace(xrng(1),xrng(2),n+1);
yunif=funInterp(xunif);
%chebyshev points
xcheb=cos((2*(0:n)+1)/(2*(n+1))*pi );
ycheb=funInterp(xcheb);
%legendre points
syms xs %use matlab symbolic toolbox
xlgndrS=vpasolve(legendreP(n+1,xs) == 0); %symbolically solve for roots
xlgndr=double(xlgndrS); %convert to double precision
ylgndr=funInterp(xlgndr);

xP=linspace(xrng(1),xrng(2),101); %x values for plotting
yP=funInterp(xP); %actual function at ypoints

%use polyfit with degree n to get nth degree polyomial interpolant
acoeff=polyfit(xunif,yunif,n);%get coefficients
yPunif=polyval(acoeff,xP); %evaluate at plot points

acoeff=polyfit(xcheb,ycheb,n);%get coefficients
yPcheb=polyval(acoeff,xP);%evaluate at plot points

acoeff=polyfit(xlgndr,ylgndr,n);%get coefficients
yPlgndr=polyval(acoeff,xP);%evaluate at plot points

%plot interpolants
figure; hold on;
plot(xP,yP,'-')
plot(xP,yPunif,':')
plot(xP,yPcheb,'--')
plot(xP,yPlgndr,'-.')
xlabel('x')
ylabel('f(x)')
legend('yP','yPunif','yPcheb','yPlgndr')

%plot interpolation error
figure; hold on;
plot(xP,yP-yPunif,':')
plot(xP,yP-yPcheb,'--')
plot(xP,yP-yPlgndr,'-.')
xlabel('x')
ylabel('Interpolation Error')
legend('yPunif','yPcheb','yPlgndr')


% Code format for L-inf norm was suggested by Google Gemini,
% Code format for L-2 norm was suggested by Mathworks
Linfunif=max(abs(yP-yPunif));
Linfcheb=max(abs(yP-yPcheb));
Linflgndr=max(yP-yPlgndr);

L2unif=norm(yP-yPunif);
L2cheb=norm(yP-yPcheb);
L2lgndr=norm(yP-yPlgndr);

% Display generated by MATLAB Copilot for Organization
% Display the results of the L-inf and L-2 norms
fprintf('L-inf norm for uniform points: %.4f\n', Linfunif);
fprintf('L-inf norm for Chebyshev points: %.4f\n', Linfcheb);
fprintf('L-inf norm for Legendre points: %.4f\n', Linflgndr);
fprintf('L-2 norm for uniform points: %.4f\n', L2unif);
fprintf('L-2 norm for Chebyshev points: %.4f\n', L2cheb);
fprintf('L-2 norm for Legendre points: %.4f\n', L2lgndr);

