% Nevilles algorithm
% Code Generated by MATLAB Copilot
function result = nevillesAlgorithm(x, y, x0) % takes in x and y data points, 
% and evaluates at x0 which is equal to xbar in this problem
n = length(x);
Q = zeros(n, n);
Q(:, 1) = y(:); % Initialize the first column with y values

for j = 2:n
    for i = 1:n-j+1
        Q(i, j) = ((x0 - x(i)) * Q(i+1, j-1) - (x0 - x(i+j-1)) * Q(i, j-1)) / (x(i+j-1) - x(i));
    end
end
result = Q(1, n); % The result is in the first row, last column
end



