% Newton's divided differences evaluated at a specific point
% Generated by Matlab Copilot
function result = newtonsDividedDifferences(x, y, xbar)
n = length(x);
divDiff = zeros(n, n);
divDiff(:, 1) = y;

for j = 2:n
    for i = 1:n-j+1
        divDiff(i, j) = (divDiff(i+1, j-1) - divDiff(i, j-1)) / (x(i+j-1) - x(i));
    end
end

% Evaluate the polynomial at the specified point
result = divDiff(1, 1);
for j = 2:n
    term = divDiff(1, j);
    for i = 1:j-1
        term = term * (xbar - x(i));
    end
    result = result + term;
end

