% Use Crout's LU decomposition without pivoting. Create algorithm
% Generated by Matlab Copilot
function [L, U] = croutLU(A)
n = size(A, 1);
L = zeros(n);
U = eye(n);

for j = 1:n
    for i = j:n
        L(i, j) = A(i, j) - L(i, 1:j-1) * U(1:j-1, j);
    end
    for i = j+1:n
        U(j, i) = (A(j, i) - L(j, 1:j-1) * U(1:j-1, i)) / L(j, j);
    end
end
end

A=[1 1+0.5*10^-15 3;2 2 20;3 6 4];
A1=croutLU(A)
R=A-A1
[L U P]=lu(A)
R_p=P.*A-A1
compare=R_p-R




