%% Exercise 5

%% Part a
x_j1=[0;1;2];
c1=fdcoeff(1,0,x_j1); % 1st Derivative Order 2 Forward Finite Difference Coefficients

x_j2=[-1;0;1];
c2=fdcoeff(1,0,x_j2); % 1st Derivative Order 2 Centered Finite Difference Coefficients

x_j3=[-2;-1;0;1;2];
c3=fdcoeff(2,0,x_j3); % 2nd Derivative Order 4 Centered Finite Difference Coefficients

% fprintf c1 c2 and c3
fprintf('c1: %s\nc2: %s\nc3: %s\n', mat2str(c1), mat2str(c2), mat2str(c3)); % Generated by MATLAB Copilot

%% Part b
f=@(x) exp(x); % Exact Function
% Evaluate the exact function and its first derivative at specified points
f_array=f(x_j3);
coeff_e=fdcoeff(1,0,x_j3) % Produce centered finite difference coefficients for 1st derivative order 4
approxderivativeexp=coeff_e*f_array

% From MATLAB class folder
x0=0;
fprimeexact1=exp(x0);
h=10.^(-1:-1:-8);
firstorderfwfd=(f(x0+h)-f(x0))./h;
errorapproxexp=abs(firstorderfwfd-fprimeexact1); % From Matlab Drive Class Folder
convergplot=polyfit(log(h),log(errorapproxexp),1);
order_convergence_exp=c(1)

%% Part c
f1=@(x) sin(x); % Set function whose derivative will be approximated
x_j12=[0;1;2;3;4]; % Set stencil points
coeff_sin=fdcoeff(1,0,x_j12) % Produce forward finite difference coefficients for 1st derivative with order 4
f_sin=sin(x_j12);
approxderivative_sin=c_sin*f_sin % 1st derivative order 4 with 5 stencil points
% This approximation is 4th order accurate. 

