%% Exercise 1
%% b)
X = [1 1 1; 0 1 1; 0 0 1]; 
Q=gram_schmidt(X) 

%% c)
X1=[1 1 1; 1 1 0; 0 0 1];
Q1 = gram_schmidt(X1)

%% d)
X2=[2 -1 0;0 -1 2;-1 0 0;-1 2 -1];
Q2=gram_schmidt(X2) 
% The matrix Q is not orthogonal because even though Q2'*Q2 equals the identity matrix I, Q2*Q2' is not I. 
% From the definition of orthogonal matrices provided by Google Gemini,
% this matrix Q is not orthogonal

function Q=gram_schmidt(X) % Declare the function for Gram Schmidt
%X = [1 1 1; 0 1 1; 0 0 1]; % Example matrix from exercise 1 problem a)
[m, n] = size(X); % Set the rows and columns equal to the size of matrix X
Q = zeros(m, n); % Initialize 0 vectors within Q
for j = 1:n % run the entire loop for 1 through n iterations
    v = X(:, j); % Begin loop with the jth column of matrix X
    for i = 1:j-1 % run inner loop from 1 to j-1 iterations
        r = Q(:, i)' * X(:, j); % Compute projection of Q onto X
        v = v - r * Q(:, i); % Subtract projection from vector v
    end
    Q(:, j) = v / norm(v); % Normalize v and save it for matrix Q
end
end
% 2 Matlab codes for gram_schmidt were generated by Matlab Copilot and combined, with adjustments
% made for problem. This was to follow algorithm sketch as close as possible. Comments were made in own words to explain algorithm.
% Needed clarification from Copilot to understand function of "'" symbol
% in Q(:,i). This link was also used to help calculate L2 norm https://mathworld.wolfram.com/L2-Norm.html